### ISSUE TITLE
Feature request: mailtrap.io as provider

### ISSUE THREAD

**Issue by tamtamchik** [omnimail/omnimail#3]
Great tool for debugging emails, should be available as providers for local/staging environments.

**Comment by stevecoug** [comment]
mailtrap.io uses SMTP as its interface

**Comment by shahariaazam** [comment]
Is this issue still valid or someone can provide documentation link about their API about how to send email. I will keep this issue open for another 1 week before closing it.

**Comment by stevecoug** [comment]
Their API simply uses SMTP, so I don't think a separate service is necessary. It's a great service, though.

**Comment by tamtamchik** [comment]
Yep, they moved to SMTP fully so no need for a separate service.
