### ISSUE TITLE
Proposal to make some improvements

### ISSUE THREAD

**Issue by shahariaazam** [omnimail/omnimail#47]
As this library is growing and developer are showing interest, it would be great if we can re-factor something (no new feature, improvement on rapid improvement).

I would like to propose few points here:

- We need to improve tests as much as possible to make sure everything is working properly after changes.

- We can remove travis and use GitHub workflow for CI to code checks, tests, etc.

- We shouldn't accept any PR without tests and pass the CI workflow

- Development related tooling is not much available for php5.5. Also its not being maintained anymore. So to keep minimum compatibility to php5.6

- Bug fix release we can make frequently but we need to focus on development branch for major release.

- All PR must be submitted to *development* branch and we will merge to *merge* based on milestone. So it will reduce frequent release and give developers some resting time to upgrade for every PR.

Most of the related changes has been prepared in my draft PR https://github.com/gabrielbull/omnimail/pull/46.

I would like to know your feedback before making any decision.

Also please feel free to add your own proposal.

Thanks in advance.

**Comment by stevecoug** [comment]
Switching from Travis to Github CI: 👍
Changing minimum to PHP 5.6: 👍

I like the idea behind using the development branch and milestones, but we should be willing to have some flexibility in timing. Also, should bug fix PRs be submitted to the development branch?

**Comment by shahariaazam** [comment]
> Switching from Travis to Github CI: 👍
> Changing minimum to PHP 5.6: 👍
> 
> I like the idea behind using the development branch and milestones, but we should be willing to have some flexibility in timing. Also, should bug fix PRs be submitted to the development branch?

**Timing flexibility:** of course. We will set goals with that in mind

**Bug Fix PRs:** IMO yes. We can accept security related PR directly to **master**. Because frequent bumping version and release will keep developer busy to adjust their softwares too. So better we can maintain milestone so everybody can know upfront about what's coming next and when. 

What do you think?

**Comment by stevecoug** [comment]
I think it would be good to also start thinking about what would be required to have a 1.0 milestone, but that should be separate from this, and will be easier once we start doing milestones.

**Comment by shahariaazam** [comment]
> I think it would be good to also start thinking about what would be required to have a 1.0 milestone, but that should be separate from this, and will be easier once we start doing milestones.

Yes. We can make a plan to release our first major version 1.0.

I will create a milestone today and please assign tickets there if you see fit.

**Comment by shahariaazam** [comment]
@gabrielbull What's your feedback about this proposal. If everything seems fine we can move forward to create issues and work on PRs.

**Comment by stevecoug** [comment]
@gabrielbull told me that he's no longer doing PHP work. Maybe as part of this we should also transition it to a community-owned project?

**Comment by gabrielbull** [comment]
I am open to transferring the project to a community owned project. Is there a community for such projects under PHP or should we create one named omnimail?

**Comment by stevecoug** [comment]
In packagist, it's already **omnimail/omnimail**, so that would probably make the most sense

**Comment by gabrielbull** [comment]
Done

**Comment by shahariaazam** [comment]
Chat room activated on https://gitter.im/omnimail/omnimail . I have sent invite to @gabrielbull  and @stevecoug

**Comment by shahariaazam** [comment]
I am going to close this issue as we all agree for this improvement and proposal accepted. 👍
