### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by eileenmcnaughton** [omnimail/omnimail#54]
I'm wanting to check in on future plans for this extension. 

Currently the minimum php version is set to 5.6 and the current supported versions 8.0 and 8.1 are not being run under CI https://www.php.net/supported-versions.php. I would suggest that a minimum version of 7.2 (unsupported as of a year ago) or 7.3 (only just unsupported) would allow keeping up to date with packages and coding style and make it easier to add support for newer versions.

I also have questions about functionality. The functionality gaps I'm hitting are
- inability to set some parameters on smtp mailer - I did just now move my PR on that from the old repo to this one
- wanting to extend the mass mailing functionality - eg. currently there are functions to retrieve recipient lists but not to create them. I can PR in some of this functionality if people are open to it but otherwise I probably need to think about other approaches in our codebase.

**Comment by gabrielbull** [comment]
Hi @eileenmcnaughton, I am no longer working on this project and if you are willing to become a contributor I would be glad to add you as one.

**Comment by eileenmcnaughton** [comment]
@gabrielbull I'm OK with that - just wanting to know if my thoughts are in line with other maintainers

**Comment by gabrielbull** [comment]
There's no active maintainers atm. I'll add you as contributor. Thanks!
